export const introduction = {
  paragraphs: [
    `Hello! Thanks for coming by!`,
    `Youngsook is a Korean diaspora artist/researcher based in London. Holding a PhD in human geography that intersects feminist geography with queer theories, Youngsook's practice expands on our relationships with places, ecosystems and interspecies communities affected by the systematic exploitation of neo-colonial operations. Under the umbrella theme of political spirituality, her socially engaged practice explores intimate aesthetics of solidarity and collective healing.`,
    `Grief has been the focus of Youngsook's recent works, posing collective grief as the process of socio-political autopsy upon structural conditions intersecting human loss with environmental destruction. <em>Not This Future</em> (2020), commemorating the Essex 39 incident rooted in the Formosa Marine Disaster; <em>In Every Bite of the Emperor</em> (2021-ongoing), the transnational weaving of neo-colonial narratives around damaged ecosystems and struggling communities; <em>The Book of Loss (2022)</em>, performative intervention for remembrance of seven lost glaciers; <em>Slow Sips with Earth</em> (2023-ongoing), engaging communities in tea mixing as a creative method of writing a prayer for broken Earth; <em>Cockles of My Heart</em> (2024), commemorating deep sea trauma and 20 years' remembrance of Morecambe Bay cockle pickers tragedy; <em>Bahami – Stories on the Plate</em> (2024), exploring the ecological impact of conflicts with Afghan refugee women, are in tandem with this enquiry.`,
    `Youngsook's works have been presented internationally. Amongst them are Arts Catalyst, Asia-Art-Activism, Barbican Centre, Bow Arts, Camden Arts Centre, Coventry Biennial 2021, Estuary Festival, FACT Liverpool, Flat Time House, GOSH Arts, Heart of Glass, Liverpool Biennial 2021, Milton Keynes Arts Centre, Milton Keynes Islamic Arts and Culture, Nottingham Contemporary, Rich Mix, S1 Artspace, Up Projects in the UK; ARKO Art Center, Seoul Mediacity Biennale 2023, Seoul Museum of Art, The Book Society in Korea; Documenta 15, Kunsthalle am Hamburger Platz in Germany; British Council, Gerimis in Malaysia; and Nextdoor ARI in Australia.`,
    `With an emphasis on collective learning and imagination, Youngsook founded the transnational eco-grief council <em>Foreshadowing</em> and co-founded the research-practice working group <em>Decolonising Botany</em>. Youngsook teaches Critical Studies at the Fine Arts Department, Goldsmiths University of London, exploring transformative pedagogy (bell hooks).`,
  ],
}
