export const introduction = {
  paragraphs: [
    `Hello! Thanks for coming by!`,
    `Youngsook is a Korean diaspora artist/researcher based in London. Holding a PhD in human geography that intersects feminist geography with queer theories, Youngsook's practice expands on our relationships with places, ecosystems and interspecies communities affected by the systematic exploitation of neo-colonial operations. Under the umbrella theme of political spirituality, her socially engaged practice explores intimate aesthetics of solidarity and collective healing.`,
    `Grief has been the focus of Youngsook's recent works, posing collective grief as the process of socio-political autopsy upon structural conditions intersecting human loss with environmental destruction. <em>Not This Future</em> (2020), commemorating the Essex 39 incident rooted in the Formosa Marine Disaster; <em>In Every Bite of the Emperor</em> (2021-ongoing), the transnational weaving of neo-colonial narratives around damaged ecosystems and struggling communities; <em>The Book of Loss (2022)</em>, performative intervention for remembrance of seven lost glaciers; <em>Slow Sips with Earth</em> (2023-ongoing), engaging communities in tea mixing as a creative method of writing a prayer for broken Earth; <em>Cockles of My Heart</em> (2024), commemorating deep sea trauma and 20 years' remembrance of Morecambe Bay cockle pickers tragedy; <em>Bahami – Stories on the Plate</em> (2024), exploring the ecological impact of conflicts with Afghan refugee women, are in tandem with this enquiry.`,
    `Youngsook's works have been presented internationally. Amongst them are Arts Catalyst, Asia-Art-Activism, Barbican Centre, Bow Arts, Camden Arts Centre, Coventry Biennial 2021, Estuary Festival, FACT Liverpool, Flat Time House, GOSH Arts, Heart of Glass, Liverpool Biennial 2021, Milton Keynes Arts Centre, Milton Keynes Islamic Arts and Culture, Nottingham Contemporary, Rich Mix, S1 Artspace, Up Projects in the UK; ARKO Art Center, Seoul Mediacity Biennale 2023, Seoul Museum of Art, The Book Society in Korea; Documenta 15, Kunsthalle am Hamburger Platz in Germany; British Council, Gerimis in Malaysia; and Nextdoor ARI in Australia.`,
    `With an emphasis on collective learning and imagination, Youngsook founded the transnational eco-grief council <em>Foreshadowing</em> and co-founded the research-practice working group <em>Decolonising Botany</em>. Youngsook teaches Critical Studies at the Fine Arts Department, Goldsmiths University of London, exploring transformative pedagogy (bell hooks).`,
  ],
}

export type WorkEntry = {
  slug: string
  title: string
  category: 'works' | 'archives'
  content: string[]
  images: { src: string; alt: string }[]
}

export const works: WorkEntry[] = [
  {
    slug: 'seasons-of-the-mouth',
    title: 'Seasons of the Mouth',
    category: 'works',
    content: [
      `<span class="image-big"><img decoding="async" class="alignnone wp-image-1165 size-large resized" src="/images/seasons-of-the-mouth-01-1024x577.png" alt="" width="768" height="433"></span><span data-preserver-spaces="true">Based on the MECAHF Project report –&nbsp;</span><em><span data-preserver-spaces="true">Food for Healthcare</span></em><span data-preserver-spaces="true">, public procurement accounts for 19% of Europe's GDP (more than €2.3 trillion annually), and the recommendation for a significant impact on food sustainability is to resource more seasonal and local ingredients. Fresher foods in season also taste better, potentially reducing food waste.&nbsp;</span>`,
      `&nbsp;<em><span data-preserver-spaces="true">Seasons of the Mouth&nbsp;</span></em><span data-preserver-spaces="true">attempts to embed the idea of phenology into the hospital foods practice. Phenology studies seasonal changes in plants and animals – budding, flowering and leaf colouring in plants, and the emergence and migration of animals. Gentle observation and witnessing document the rhythms of the ecosystem and detect any cautious changes or extinction, hence a critical method for ecological grief.</span>`,
      `<span data-preserver-spaces="true">The process engaged out/in-patient children and catering staff in the Great Ormond Street Hospital for Children. A set of creative activities accommodated conversations around the understanding of seasons, favourite seasonal foods and food memories of participating children. Aided by the palette of seasonal food ingredients, these conversations also imagined the season-sensitive menus for the hospital food provision.&nbsp;</span>`,
      `<span class="image-big"><img decoding="async" class="alignnone wp-image-1164 size-large resized" src="/images/seasons-of-the-mouth-03-1024x575.png" alt="" width="768" height="431"></span>`,
      `<span data-preserver-spaces="true">However, it was heartbreaking attending to the worrying voices of kitchen staff who try their best to include seasonal local foods in the menu yet feel overpowered by the impact of the exploitative global foods trade. Although their capacity to bring fundamental changes feels limited by much larger systematic culpability, their compassion for sustainable food practices has been explicit by introducing various cultural celebrations. So do most children identify seasonal foods through festivities and celebrations!&nbsp;</span>`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="alignnone wp-image-1167 size-large resized" src="/images/seasons-of-the-mouth-04-1024x574.png" alt="" width="768" height="431"></span>`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="alignnone wp-image-1168 size-large resized" src="/images/seasons-of-the-mouth-05-1024x574.png" alt="" width="768" height="431"></span>`,
      `<span data-preserver-spaces="true">It is one good learning as most sustainability narratives are often heavily carbon footprint-centred, with a lack of recognition of diversity as a critical factor for creative and healthy community-led solutions. Here, the remit of phenological practice expands from observation of ecological cycles to embodied seasonal encounters in rituals, folklores, and the joy of food sharing.</span>`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="alignnone wp-image-1163 size-large resized" src="/images/seasons-of-the-mouth-06-1024x577.png" alt="" width="768" height="433"></span> <span class="image-big"><img loading="lazy" decoding="async" class="alignnone wp-image-1162 size-large resized" src="/images/seasons-of-the-mouth-07-1024x576.png" alt="" width="768" height="432"></span>`,
      `<span data-preserver-spaces="true">* Culminated in a video 'Seasons of the Mouth', exhibited in the GOSH corridor.</span>`,
      `<span data-preserver-spaces="true">* Commissioned by GOSH Arts (2023).</span>`,
    ],
    images: [
      { src: '/images/seasons-of-the-mouth-02-2000x1435.png', alt: '' },
      { src: '/images/seasons-of-the-mouth-01-1024x577.png', alt: '' },
      { src: '/images/seasons-of-the-mouth-03-1024x575.png', alt: '' },
      { src: '/images/seasons-of-the-mouth-04-1024x574.png', alt: '' },
      { src: '/images/seasons-of-the-mouth-05-1024x574.png', alt: '' },
      { src: '/images/seasons-of-the-mouth-06-1024x577.png', alt: '' },
      { src: '/images/seasons-of-the-mouth-07-1024x576.png', alt: '' },
    ],
  },
  {
    slug: 'book-of-loss',
    title: 'Book of Loss',
    category: 'works',
    content: [
      `<span class="image-big"><img decoding="async" class="alignnone wp-image-1158 size-large resized" src="/images/book-of-loss-Youngsook-2-1024x683.jpg" alt="" width="768" height="512"></span>`,
      `<em><span data-preserver-spaces="true">Book of Loss</span></em><span data-preserver-spaces="true">&nbsp;is the intervention act for the party. It commemorates the seven glaciers lost in recent years. The figures of glaciers are drawn secretly on wine glasses with a UV Marker. The drawing would only reveal when the UV light sheds on. The glasses are served randomly with drinks to the guests. The intervention is navigating through the crowd to find them. Whenever I discover the hidden glacier, I open the Book of Loss and, with the guest holding the glass, read the bit about that particular glacier and discuss the impact of its loss. It is about creating an intimate ephemeral moment of ecological grief and quietly holding the space for all the livelihoods affected by the loss of glaciers in the middle of the hustle-bustle.&nbsp;</span>`,
      `<span data-preserver-spaces="true">So, let me know if you plan to host the party with policymakers or influential people. I will be there with my Book of Loss.&nbsp;&nbsp;</span>`,
      `<span data-preserver-spaces="true">* Commissioned by UP Projects (2022) </span>&nbsp;&nbsp;`,
    ],
    images: [
      { src: '/images/book-of-loss-Youngsook-Book-of-Loss-2022-2000x1500.jpg', alt: '' },
      { src: '/images/book-of-loss-Youngsook-2-1024x683.jpg', alt: '' },
    ],
  },
  {
    slug: 'in-every-bite-of-the-emperor-prologue',
    title: 'In Every Bite of the Emperor – Prologue',
    category: 'works',
    content: [
      `<span class="image-big"><img decoding="async" class="aligncenter wp-image-968 size-large resized" src="/images/in-every-bite-of-the-emperor-prologue-offering_Y.Choi_-1024x350.png" alt="" width="768" height="263"></span>`,
      `<em>In Every Bite of the Emperor</em> is the ongoing long term project about ecological grief. It aims to create the space of inter-species healing and solidarity by weaving through different geographical sites that share the pain of ecological trauma and broken communities. The prologue is written as the first processual residue of the project after the initial research around the subject. The following is the performative reading and transcript of it.`,
      `&nbsp;`,
      `And the list of losses goes on<br>On and on, and on and on, and on and on…<br>My father warned me<br>Don't go near seashore<br>There is a horror you cannot bear<br>Of course, I didn't listen to him<br>Seventy tons of dead fish<br>No sign of life<br>I see my reflection in<br>their rotting eyes<br>I wear indescribable stinks of<br>their intoxicated flesh<br>I can hardly breathe<br>Chest pain wet cheeks<br>But father, if I don't witness this<br>Where my blind sight would take me<br>—<br>In October 2019, 39 people were found dead in the back of a lorry in Essex. They died in suffocation whilst trying to cross the UK border illegally. The Home Office and the media quickly agreed to condemn people smugglers as a cause of this tragedy. However, the mainstream narratives around this incident did not acknowledge most victims are from two fishing villages in Vietnam where the marine ecosystem is completely destroyed. The multi-national steel corporate directly dumped their toxic waste into the ocean. Fishing became impossible. Tourism quickly died out. Most people in these two villages lost their livelihood and became people smugglers' targets. Desperate young people decided to take a risk to help their families survive and follow their dreams.`,
      `The youngest victim was only 15 years old.<br>—<br>When Franz Fanon says 'I entered the list', I immediately think of death. Death of all kinds of lives and, of course, death of stories. Adrienne Maree Brown says 'grief is not linear and it is everywhere.' If grief is everywhere, they must be connected here and there. I have been looking for these dots.`,
      `<img decoding="async" class="aligncenter wp-image-974 size-large" src="/images/in-every-bite-of-the-emperor-prologue-Great_Chain_of_Being-710x1024.png" alt="" width="710" height="1024">`,
      `God-Angels-Humans-Animals-Plants-Minerals<br>God-Angels-Humans (read in a tone of emphasis)-Animals-Plants-Minerals<br>God-Angels-Humans (read in a tone of more emphasis) -Animals-Plants-Minerals`,
      `'The Great Chain of Being', in this medieval order of the world, everything descends from God. Carl Linnaeus, a revered botanical scientist, spent his whole life refining the taxonomic system for nature. First, he removed the spiritual sphere from the world of science. Without God, without angels, the hierarchy of his science kingdom descends from a very specific human variety – Europaeus Albus, white European along with sub racial species of red Americana, tawny Asiana and black Africana. The white European became the equation to God. Since then, the world has had to follow their order and serve them.`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="aligncenter wp-image-1085 resized" src="/images/in-every-bite-of-the-emperor-prologue-meateaters.png" alt="" width="768" height="565"></span><br>In 1872 Japan, the Meiji Emperor ingested meat in public as part of the New Year's celebration. Proposing the West as the cultural superior, westernisation was accelerated in the Meiji era, including the ambition of transforming Asian bodies into western ones. This transformation wasn't just about cutting hairs short and changing into the Victorian attires but also about everyday diet. Meat-centred western food consumption was declared as a national benefit in times meat-eating was a social taboo. It was a forceful institutional gesture.`,
      `I imagine myself as one of the spectators, quietly witnessing my emperor chewing the red meat and dismissing 900 years old social taboo. I foresee wiping out the forest, the slaughtering of trees and floras and species inhabiting them. In every bite of the emperor, I feel the blood filling up in my mouth. The taste of westernisation, the taste of great empire.`,
      `I feel sick.&nbsp;<br><br>`,
      `<small><span class="image-big"><img loading="lazy" decoding="async" class="aligncenter wp-image-972 size-large resized" src="/images/in-every-bite-of-the-emperor-prologue-Screenshot-2022-09-13-at-14.04.51-1024x380.png" alt="" width="768" height="285"></span><i></i></small>`,
      `When you become a widow, you see widows everywhere.<br>When you lament, the ghost becomes no longer a stranger.<br>Every loss directs us to all other worlds co-existing.<br>They are beyond our eyes, beyond Latin alphabets.<br>History might select a few but the story needs all of us.<br>The story, not from your head, but your belly.<br>—<br>The field was full of bright yellow spots – a calling from dandelions. I imagined the bitter salad, tea and liquor, containing mineral goodness. I imagined my hands touching the wet soil, tightly cuddling around dandelion roots. I thought of my mother. She always manages to forage something regardless of the season whenever we go to the mountain together. I started digging up to harvest a few dandelions. But soon, a man with angst approached me.`,
      `"Excuse me! I am the keeper of this garden. What are you doing here?"<br>"I am just harvesting a few dandelions."`,
      `The man started raising his voice. "Can you not see you are irritating the landscape? There was nothing here before I came. I secured the funding and have been working hard to create and protect this ecosystem. And now, you are destroying it!"`,
      `I was frightened and quickly hid my dirty hands and dandelions behind my back.<br>"Sorry, I didn't know."`,
      `At that moment, it wasn't just the scolding man who upset me. The whole situation must have been comic to these dandelions as I heard them laughing and giggling, and saying, "Who protects whom?" "Did he just say nothing was here before he came?" I wished it wasn't just me who could hear the dandelion voices. I wished that the man could understand the land he is standing on is beyond his capacity of protection, or destruction, and certainly beyond the funding schemes for conservation.<br><br>`,
      `<small><span class="image-big"><img loading="lazy" decoding="async" class="aligncenter wp-image-973 size-large resized" src="/images/in-every-bite-of-the-emperor-prologue-Screenshot-2022-09-13-at-14.12.16-1024x536.png" alt="" width="768" height="402"></span></small>`,
      `In 2014, the elders of Sampyounglee, a small farming village in Korea, gathered around their shaman tree. The purpose of this gathering is to call for protesting against the government plan to install the high-pressure transmission towers across their spiritual land. Two towers were scheduled to be built in this village, one in the No-In mountain where the community rituals are often held and the other, just behind this shaman tree. The construction for the first tower launched already with a series of explosion that upset the spiritual mountain. A few days later, the village suffered from the excessive amount of hail. It damaged all the orchards and onion fields. In that year, famers' income declined to almost zero. The elders see it as a curse. Without funded scientific research and all those complicated numbers, the elders just know this is the result of ecological disruption and human's arrogance and exploitation towards nature. The villagers are asking the mountain for forgiveness and praying to the tree for protection from further destructive progression.`,
      `Cleary, our elders' trust is not on the state authority but on their ancestral tree and mountain who came to this world before them. The grandmothers recognise the importance of forming inter-species solidarity, calling not only humans but also all spirits of nature. Anna Tsing, in her book "the mushroom at the end of the world', says that gathering becomes happening when the self starts getting 'contaminated' by the others – the indeterminate moments of self-and-other transformation. The elders were trying to shape their transformative moment by blurring not only self-and-other but also humans and non-humans, the material and the spiritual.<br>—`,
      `And I am here with a list, that is almost never-ending.<br>I beg you, not to give up, reading&nbsp;<i>every</i>&nbsp;name on it.`,
      `—`,
      `* <i>In Every Bite of the Emperor </i>has been supported by Heart of Glass, UK.`,
      `* The first iteration of this prologue was performed in <a href="https://www.coventrybiennial.com/events/beyond-the-anthropocene-parallel-state/" target="_blank" rel="noopener"><em>Beyond the Anthropocene</em> by Parallel State in the Coventry Biennial 2021 – Hyper Possible</a>. The reiteration has been presented in the living library <em>Make Interspecies Relations</em> (2022) for Nextdoor ARI, Australia, Seoul Museum of Art exhibition <i>Exceptional Times and Uncertain Moves</i> (2023), and Heart of Glass annual art conference <i>With For About</i> 2023.`,
      `* The excerpt of the prologue has been published in <em>The Minutes of the Hildegard von Bingen Society for Gardening </em><em>Companions</em> (Printed Matters, New York and London 2022), edited by Sophie Seita, Naomi Woo and Yael Ort-Dinoor.&nbsp;`,
    ],
    images: [
      { src: '/images/in-every-bite-of-the-emperor-prologue-3B99F54D-7D10-4337-93D8-AE969DD58978_1_102_o-1773x1500.jpeg', alt: '' },
      { src: '/images/in-every-bite-of-the-emperor-prologue-offering_Y.Choi_-1024x350.png', alt: '' },
      { src: '/images/in-every-bite-of-the-emperor-prologue-Great_Chain_of_Being-710x1024.png', alt: '' },
      { src: '/images/in-every-bite-of-the-emperor-prologue-meateaters.png', alt: '' },
      { src: '/images/in-every-bite-of-the-emperor-prologue-Screenshot-2022-09-13-at-14.04.51-1024x380.png', alt: '' },
      { src: '/images/in-every-bite-of-the-emperor-prologue-Screenshot-2022-09-13-at-14.12.16-1024x536.png', alt: '' },
    ],
  },
  {
    slug: 'refusing-oasis',
    title: 'Refusing Oasis',
    category: 'works',
    content: [
      `<span class="image-big"><img decoding="async" class="aligncenter wp-image-960 size-large resized" src="/images/refusing-oasis-mami-garden-1024x683.jpg" alt="" width="768" height="512"></span>`,
      `<span class="image-big"><img decoding="async" class="aligncenter wp-image-957 size-large resized" src="/images/refusing-oasis-connecting-thru-waves-1024x683.jpg" alt="" width="768" height="512"></span>`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="aligncenter wp-image-958 size-large resized" src="/images/refusing-oasis-beetroot-act-1024x647.jpg" alt="" width="768" height="485"></span>`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="aligncenter wp-image-956 size-large resized" src="/images/refusing-oasis-hands-youngsooklaura-1024x683.jpg" alt="" width="768" height="512"></span>`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="aligncenter wp-image-955 size-large resized" src="/images/refusing-oasis-hands-taey-1024x683.jpg" alt="" width="768" height="512"></span>`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="aligncenter wp-image-959 size-large resized" src="/images/refusing-oasis-hands-mami-1024x704.jpg" alt="" width="768" height="528"></span>`,
      `Held in Tuan Mami's <em>Vietnamese Immigrating Garden</em>, this gentle-paced durational performance navigates different experiences of solidarity for anti-colonial struggle, collective unsettlings and multivocal ceremonies. Feeling through interdependencies for enduring joy, grief, refusal and anger – perhaps speculative, perhaps unbearable, perhaps love, the audience is invited to enter the garden to work together towards havens, somatic solidarities, and crossings for ongoing journeys under and above ground. Staging the defence of Bungkalan farmers movement on the piece of land damaged by industrial exploitation in the city associated with arms manufacturing, <em>Refusing Oasis</em> honours the hands that touch the soil and reclaims the earth for those who dig it.`,
      `* Collaborative performance by Decolonising Botany Working Group (Laura Burns, Youngsook Choi, Cian Dayrit, Taey Iohe, Ayesha Keshani, Tuan Mami and Helen Pritchard)`,
      `* <a href="https://documenta-fifteen.de/kalender/decolonising-botany-constellations/" target="_blank" rel="noopener">Presented at W22, Document 15</a>&nbsp;Kassel Germany (2022)`,
      `* Supported by <a href="https://nhasan.org/" target="_blank" rel="noopener">Nhà Sàn Collective</a> and <a href="https://www.ba-bau.org/" target="_blank" rel="noopener">ba-bau AIR&nbsp;</a><br><br>`,
    ],
    images: [
      { src: '/images/refusing-oasis-refusingoasis.jpg', alt: '' },
      { src: '/images/refusing-oasis-mami-garden-1024x683.jpg', alt: '' },
      { src: '/images/refusing-oasis-connecting-thru-waves-1024x683.jpg', alt: '' },
      { src: '/images/refusing-oasis-beetroot-act-1024x647.jpg', alt: '' },
      { src: '/images/refusing-oasis-hands-youngsooklaura-1024x683.jpg', alt: '' },
      { src: '/images/refusing-oasis-hands-taey-1024x683.jpg', alt: '' },
      { src: '/images/refusing-oasis-hands-mami-1024x704.jpg', alt: '' },
    ],
  },
  {
    slug: 'tayeb',
    title: 'Tayeb طيب',
    category: 'works',
    content: [
      `<span class="image-big"><img decoding="async" class="aligncenter wp-image-942 size-large resized" src="/images/tayeb-IMG_8865-768x1024.jpg" alt="" width="768" height="1024"></span>`,
      `<span class="image-big"><img decoding="async" class="aligncenter wp-image-937 size-large resized" src="/images/tayeb-IMG_8608-1007x1024.jpg" alt="" width="768" height="781"></span>`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="aligncenter wp-image-938 size-large resized" src="/images/tayeb-IMG_8833-1024x768.jpg" alt="" width="768" height="576"></span>`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="aligncenter wp-image-941 size-large resized" src="/images/tayeb-IMG_8862-1024x524.jpg" alt="" width="768" height="393"></span>`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="aligncenter wp-image-940 size-large resized" src="/images/tayeb-IMG_8860-1024x585.jpg" alt="" width="768" height="439"></span>`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="aligncenter wp-image-943 size-large resized" src="/images/tayeb-IMG_8866-768x1024.jpg" alt="" width="768" height="1024"></span>`,
      `<em>Tayeb&nbsp;طيب – Stories On the Plate</em> looks into food as a medium for narrating the journey of building care structure and community solidarity amongst Syrian and Afghanistan refugee women. This community-oriented project pays attention to women's pivotal roles in refugee/migrant families, often overlooked and trivialised, even though their effort in building friendship and sisterhood is fundamental for making a new home, resilient survival and community building.&nbsp;`,
      `The project sailed off with the Persian New Year celebration 'Nowruz'. In the first workshop, the participants decorated Sholeh Zard, a rice pudding shared with neighbours during this festive season and Ramadan, with the Haft-Mewa, seven dried nuts and fruits, honouring the Afghan tradition, with the addition of rosebuds to bring more joy. Saffron yellow brightness and the irresistible fragrance of cardamom and rosewater teleport your body to Zoroastrian times. We also learned about the Egyptian Spring festival Sham El-Nessim, meaning 'smelling the breeze' and hence a picnic is an essential part. How gorgeous! The following workshops included water colouring of the most celebratory family dish on the postcard painted with edible fragrances, an embroidery session for narrating food-related heritage on the four corners of the napkin, a tea mixing session for knowledge sharing of folk healing and personalised remedies, and finally drawing session for imaginary dinner table, inspired by the generosity of Ramadan culture.`,
      `The stories gathered from the workshops were translated into a poetry book with the illustration. The poetry book was shared/served in the installation in a form of a long dining table, filled with soil bed, curious objects and plants, during the Arts in the Park Festival 2022.`,
      `* Poetry book collaboration with Nia Fekri`,
      `* Commissioned by MK Islamic Arts and Culture for the Arts in the Park 2022.`,
    ],
    images: [
      { src: '/images/tayeb-IMG_8602-2000x1500.jpg', alt: '' },
      { src: '/images/tayeb-IMG_8865-768x1024.jpg', alt: '' },
      { src: '/images/tayeb-IMG_8608-1007x1024.jpg', alt: '' },
      { src: '/images/tayeb-IMG_8833-1024x768.jpg', alt: '' },
      { src: '/images/tayeb-IMG_8862-1024x524.jpg', alt: '' },
      { src: '/images/tayeb-IMG_8860-1024x585.jpg', alt: '' },
      { src: '/images/tayeb-IMG_8866-768x1024.jpg', alt: '' },
    ],
  },
  {
    slug: 'circle-of-care',
    title: 'Circle of Care',
    category: 'works',
    content: [
      `<span class="image-big"><img decoding="async" class="aligncenter wp-image-914 size-large resized" src="/images/circle-of-care-care-totems-1024x728.jpg" alt="" width="768" height="546"></span>`,
      `<span class="image-big"><img decoding="async" class="aligncenter wp-image-915 size-large resized" src="/images/circle-of-care-Linda-Quote-1024x678.jpeg" alt="" width="768" height="509"></span>`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="aligncenter wp-image-916 size-large resized" src="/images/circle-of-care-Care-Crosswords-1024x678.jpeg" alt="" width="768" height="509"></span>`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="aligncenter wp-image-919 size-large resized" src="/images/circle-of-care-Screenshot-2022-09-12-at-21.06.23-1024x550.png" alt="" width="768" height="413"></span>`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="aligncenter wp-image-920 size-large resized" src="/images/circle-of-care-video-still-02-1024x550.png" alt="" width="768" height="413"></span>`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="aligncenter wp-image-918 size-large resized" src="/images/circle-of-care-performance03-1024x683.jpeg" alt="" width="768" height="512"></span>`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="aligncenter wp-image-917 size-large resized" src="/images/circle-of-care-performance02-1024x683.jpeg" alt="" width="768" height="512"></span>`,
      `Touching upon our circular relations to care practices, <em>Circle of Care</em> challenges the 'caring/being cared' binary as our life situations constantly shift us between these two. Also, the caring relationship is often reciprocal rather than one way. The narratives are drawn from a series of workshops with care home seniors. We discussed what care means around objects that carry significant memories or everyday practice of care, made the 'care tree' that depicts various care relationships, debated what makes us vulnerable and hence builds strength whilst making care totems, and we looked into the institutional care system and the reality of the care industry.`,
      `These conversations were activated and shared&nbsp; through the performance <a href="https://camdenartcentre.org/whats-on/circle-of-care-from-it-matters-what-happens-next" target="_blank" rel="noopener" class="broken_link">'Circle of Care' at Camden Arts Centre</a>, with the launch of the Care Crosswords! The game board with a QR code that leads to the clues has been displayed on the garden wall of Camden Arts Centre, which is also downloadable from their website.`,
      `* Commissioned by Camden Arts Centre, curated by the RCA Curating Contemporary Art 2021 for the group show <em>It Matters What Happens Next</em>`,
      `* Special thanks to the Springdene Care Home artist resident Odile Kidd and all our workshop participants!!!<br><br>`,
      `&nbsp;`,
    ],
    images: [
      { src: '/images/circle-of-care-performance01-2000x1500.jpeg', alt: '' },
      { src: '/images/circle-of-care-care-totems-1024x728.jpg', alt: '' },
      { src: '/images/circle-of-care-Linda-Quote-1024x678.jpeg', alt: '' },
      { src: '/images/circle-of-care-Care-Crosswords-1024x678.jpeg', alt: '' },
      { src: '/images/circle-of-care-Screenshot-2022-09-12-at-21.06.23-1024x550.png', alt: '' },
      { src: '/images/circle-of-care-video-still-02-1024x550.png', alt: '' },
      { src: '/images/circle-of-care-performance03-1024x683.jpeg', alt: '' },
      { src: '/images/circle-of-care-performance02-1024x683.jpeg', alt: '' },
    ],
  },
  {
    slug: 'noguchi-encounter',
    title: 'Noguchi Encounter',
    category: 'works',
    content: [
      `<span data-preserver-spaces="true"><span class="image-big"><img decoding="async" class="aligncenter wp-image-902 size-large resized" src="/images/noguchi-encounter-IMG_8120-892x1024.jpg" alt="" width="768" height="882"></span></span>`,
      `<span class="image-big"><img decoding="async" class="aligncenter wp-image-903 size-large resized" src="/images/noguchi-encounter-IMG_8140-768x1024.jpg" alt="" width="768" height="1024"></span>`,
      `<span data-preserver-spaces="true">In September 2021, Barbican Centre featured an exhibition celebrating Japanese American sculptor Isamu Noguchi. The civic sculpture workshop </span><em><span data-preserver-spaces="true">Reciprocal Landscape</span></em><span data-preserver-spaces="true"> was operated in conjunction with it. Inspired by Noguchi's belief – sculpture should not be restricted to the eyes only, it should be used and played, the opposite approach of 'do not touch' 'do not climb', the family participants reciprocated with the works created from the previous session(s) with the introduction of different materials and techniques. The temporary civic sculpture park slowly emerged in the garden room of Barbican Centre with a great collection of works that evolved throughout the day. The cherry on top of the workshop was the pirate moment of smuggling one of the collectively created sculptures into the main gallery where Noguchi's works were displayed, complimenting and completing the ideal of civic sculpture.&nbsp;</span>`,
      `<span data-preserver-spaces="true">Another engagement during the exhibition is the letter exchange project&nbsp;</span><a class="editor-rtfLink" href="https://sites.barbican.org.uk/noguchi-resonances-december-despatch/" target="_blank" rel="noopener"><em><span data-preserver-spaces="true">Noguchi Resonance</span></em></a><span data-preserver-spaces="true">. Taking up Noguchi's idea of earth citizen – 'belonging anywhere but nowhere', my correspondence narrates through the liminal identity that goes beyond geographical and cultural barriers, yet bonds with nature both materially and spiritually. Here are some excerpts from it:</span>`,
      `<span data-preserver-spaces="true">"This Conservatory accommodates more than 1,500 species displaced from all over the world, including palm trees, banana plants and a cactus collection. It can feel quite magnificent to be in this human-made Eden, walled in by glass panels, if you turn a blind eye to how a botanical garden often exists due to the violent legacies of an extractive colonial practice, with its knowledge production based on the ignorance of indigenous people's wisdom, histories and harmonious relationship to nature, the brutal displacement of life forms, and profiteering out of exoticising foreign species. And yet, the majestic feeling I have in this urban oasis is genuine as I witness all the plants that have migrated from different parts of the world to survive so beautifully together. They are especially beautiful whilst gently tendered by Noguchi's Araki Cloud during the course of the exhibition. I realise that the human aspiration to rebuild Eden is impossible without the resilience and effort of the displaced in co-survival and homemaking with other species of various origins."</span>`,
      `<span data-preserver-spaces="true">"Noguchi's identification as a 'citizen of the earth' also reminds me of my residency at Hawkwood College last May, where I explored the decolonising methods for reconnecting with nature. During the residency, I walked in the green fields that surrounded the College every morning. I sought the different areas of landscapes, smells, textures and energies, where I laid down on the ground and untied my hair. My hair is one of the few ever-growing parts of my body, which I used to make an anchor to Mother Earth. Being replanted like this to the land myself in these moments enabled me to forget about all the borders and hierarchies that socially construct and define who I am with my birth certificate, passport, language and cultural affinities. It felt like finally coming home."</span>`,
      `* Reciprocal Landscape, co-facilitated with Eva Freeman`,
      `* Noguchi Resonance, curated by Annie Yael Kwan`,
      `* Both works commissioned by Barbican Centre&nbsp;&nbsp;`,
    ],
    images: [
      { src: '/images/noguchi-encounter-IMG_8122-2000x1500.jpg', alt: '' },
      { src: '/images/noguchi-encounter-IMG_8120-892x1024.jpg', alt: '' },
      { src: '/images/noguchi-encounter-IMG_8140-768x1024.jpg', alt: '' },
    ],
  },
  {
    slug: 'becoming-forest',
    title: 'Becoming Forest',
    category: 'works',
    content: [
      `<span class="image-big"><img decoding="async" class="aligncenter wp-image-888 size-large resized" src="/images/becoming-forest-IMG_7465-1024x950.jpg" alt="" width="768" height="713"></span>`,
      `<span class="image-big"><img decoding="async" class="aligncenter wp-image-885 size-large resized" src="/images/becoming-forest-IMG_6764-768x1024.jpg" alt="" width="768" height="1024"></span>`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="aligncenter wp-image-886 size-large resized" src="/images/becoming-forest-2-1024x768.jpg" alt="" width="768" height="576"></span>`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="aligncenter wp-image-887 size-large resized" src="/images/becoming-forest-3a1df522-1511-44b2-82a9-dd7c505791a3-1024x693.jpg" alt="" width="768" height="520"></span>`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="aligncenter wp-image-891 size-large resized" src="/images/becoming-forest-Becoming-Forest-1024x735.png" alt="" width="768" height="551"></span>`,
      `<em>Becoming Forest</em> is the community-oriented healing project focusing on mental health issues accelerated by Covid-19. Drawing upon Franz Fanon's seminal observation on the relationship between colonial oppression/violence and mental illness, Becoming Forest conceptualises collective healing as performing justice. It aims to build the solidarity circle of care specifically for Southeast and East Asian refugees and precarious migrants.`,
      `Articulating collective healing as migrant justice practice, the participatory process of the project tests out the concept of 'folk healing', which emphasises participants' cultural common grounds as a critical healing factor and weighs on equally both verbal and nonverbal communications. The folk healing approach also counters the limitations of western psychotherapy based on individualised pathologisation, rather than interrogating socio-structural issues around one's mental status, and overcomes patient-healer binary.`,
      `Seeing collective healing as a slow, empathetic and ecological process, Becoming Forest positions nature and time as key healers. Going over the full cycle of year-round, the project spans with a series of seasonal walks and creative workshops over digital spaces between forest gatherings. After two years of experimental journey with a dedicated group of participants, the project published the toolkit for sharing the grass-root knowledge and diaspora healing methods. It is accessible via the resources section of <a href="https://www.eseahub.co.uk/community-responses/breakwater-toolkit" target="_blank" rel="noreferrer noopener">ESEA Hub</a>.`,
      `Becoming Forest has extended its reach by taking up the Arts Catalyst Residency, setting up the ESEA diaspora sonic space of solidarity and comfort through producing four episode for each of four seasons. It starts with the <a href="https://audioboom.com/posts/7872810-artist-broadcast-breakwater-youngsook-choi-and-taey-iohe-and-c-ng-ph-m-becoming-forest" target="_blank" rel="noreferrer noopener">Winter Episode</a> that explores Filipino diaspora sonic space, including interview of&nbsp; Michaele Nagac, a mental health support officer at Kanlungan Filipino Consortium to discuss the colonial implication of mental health problems and how we associate sound and memory for the healing process. <a href="https://audioboom.com/posts/7955547-breakwater-youngsook-choi-and-taey-iohe-and-c-ng-ph-m-becoming-forest-spring-episode" target="_blank" rel="noreferrer noopener">Spring Episode</a> invites listeners to enjoy a polyphonic spring day, featuring birdsong, buzzing bees, weather, and East Asian folk songs and Vietnamese folk tale, interlaced with an interview with Jack Shieh, the director of Vietnamese Mental Health Services, who has dedicated almost 40 years to community work in the UK.&nbsp;`,
      `<a rel="noreferrer noopener" href="https://audioboom.com/posts/8058487-breakwater-youngsook-choi-and-taey-iohe-and-c-ng-ph-m-becoming-forest-summer" target="_blank">Summer Episode</a> aims to hold a space of solidarity and communal comfort for Hong Kong diasproa communities, inviting listeners to a conversation held during a communal hotpot meal where the UK based artists with Hong Kong heritage – Bettina Fung 馮允珊, Yarli Allison, and Yin Lo – share their thoughts on food, homemaking, language, migration, decolonisation and more. The last <a rel="noreferrer noopener" href="https://artscatalyst.org/broadcast/becoming-forest-autumn/" data-type="URL" data-id="https://artscatalyst.org/broadcast/becoming-forest-autumn/" target="_blank">Autumn Episode</a> is a gift of the collective playlist put forward by the Becoming Forest community members. Each track is intersected with the short story explaining why this song is special to their particular lived experience as migrants and how it is relevant to their current life trajectories.`,
      `* Collaboration with Taey Iohe`,
      `* Radio production with Cường Phạm, with support from Kitty Turner &amp; Lori E. Allen`,
      `* In partnership with Southeast and East Asian Centre and Kanlungan Filipino Consortium.`,
      `* The project is the recipient of Arts Council England Project Grant, with the additional support from a-n Time Space Money bursary and Arts Catalyst Radio Residency bursary.`,
    ],
    images: [
      { src: '/images/becoming-forest-IMG_7904-2000x1500.jpg', alt: '' },
      { src: '/images/becoming-forest-IMG_7465-1024x950.jpg', alt: '' },
      { src: '/images/becoming-forest-IMG_6764-768x1024.jpg', alt: '' },
      { src: '/images/becoming-forest-2-1024x768.jpg', alt: '' },
      { src: '/images/becoming-forest-3a1df522-1511-44b2-82a9-dd7c505791a3-1024x693.jpg', alt: '' },
      { src: '/images/becoming-forest-Becoming-Forest-1024x735.png', alt: '' },
    ],
  },
  {
    slug: 'fermented-flower',
    title: 'Fermented Flower',
    category: 'works',
    content: [
      `<span class="image-big"><img decoding="async" class="aligncenter wp-image-860 size-large resized" src="/images/fermented-flower-B0F14BFA-CF96-4B4F-AD78-9DA90D2E3349-997x1024.jpg" alt="" width="768" height="789"></span>`,
      `<span class="image-big"><img decoding="async" class="aligncenter wp-image-859 size-large resized" src="/images/fermented-flower-8F5B9532-D02D-472A-95E8-FFF50332B58F-997x1024.jpg" alt="" width="768" height="789"></span>`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="aligncenter wp-image-861 size-large resized" src="/images/fermented-flower-C87D2893-298F-4BB6-9993-E7CE9AAB8F95-997x1024.jpg" alt="" width="768" height="789"></span>`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="aligncenter wp-image-869 size-large resized" src="/images/fermented-flower-Yello-Furry-Lullaby-liquor-1024x526.png" alt="" width="768" height="395"></span>`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="aligncenter wp-image-864 size-large resized" src="/images/fermented-flower-Fermented-Flower-2021-full-view-1024x768.jpg" alt="" width="768" height="576"></span>`,
      `<em>Fermented Flower&nbsp;</em>presents a textile and audio installation, installed in a soil bed along with a dandelion liquor. The woven tapestry composites images drawn from archival research, with reference to the painful history of Chinese indentured labour, as part of a longer perspective on black slavery systems and the ongoing exploitation of migrant workers. The core narrative of weaving is based on one particular Korean shamanistic tradition that utilises flora to draw in, and then expel, the spirit of madness and resentment which arises from suffering. This is detailed in the appliqué of cockles in reference to the Morecambe Bay cockling disaster of 2004, alongside the names of the Chinese victims, and the hand-embroidered healing motifs of dandelion and the holmskioldia plant, reclaimed from its colloquial racist name – Coolie Cap.`,
      `The detailed tapestry and accompanying audio of symbolic bell chimes evoke references of traditional Asian religious murals, which situate scenarios and storylines to form a spiritual and earthly cosmology, conspiring an alternative planetary ancestry that dissolves prejudicial categories and hierarchies, allowing interspecies care.`,
      `* Installation composed of 3m wide x 2m high embroidered tapestry, sound, and dandelion liquor on the soil bed that spills approx 5m wide.`,
      `* Collaboration with Taey Iohe`,
      `* Commissioned by FACT Liverpool with the support of public funds from Arts Council England, Liverpool City Council, and the European Union's Horizon 2020 research and innovation programme project Artsformation.`,
      `* Exhibited in <a href="https://www.fact.co.uk/artwork/fermented-flower"><em>Future Ages Will </em></a><em><a href="https://www.fact.co.uk/artwork/fermented-flower" target="_blank" rel="noreferrer noopener">Wonder</a></em><a href="https://www.fact.co.uk/artwork/fermented-flower"> </a>(FACT 2021, UK) curated by Annie Yael Kwan / <em>Local in Making</em> 일시적 개입 (ARKO Art Centre 2022, Korea).`,
      `* <em>Fermented Flower</em> was featured in the ArtAsiaPacific magazine March/April issue in the spotlight section 'Up Close'.`,
    ],
    images: [
      { src: '/images/fermented-flower-4B3A551D-6748-41AC-89C3-08A2F9675F4B.jpg', alt: '' },
      { src: '/images/fermented-flower-B0F14BFA-CF96-4B4F-AD78-9DA90D2E3349-997x1024.jpg', alt: '' },
      { src: '/images/fermented-flower-8F5B9532-D02D-472A-95E8-FFF50332B58F-997x1024.jpg', alt: '' },
      { src: '/images/fermented-flower-C87D2893-298F-4BB6-9993-E7CE9AAB8F95-997x1024.jpg', alt: '' },
      { src: '/images/fermented-flower-Yello-Furry-Lullaby-liquor-1024x526.png', alt: '' },
      { src: '/images/fermented-flower-Fermented-Flower-2021-full-view-1024x768.jpg', alt: '' },
    ],
  },
  {
    slug: 'yellow-furry-lullaby',
    title: 'Yellow Furry Lullaby',
    category: 'works',
    content: [
      `<span class="image-big"><img decoding="async" class="aligncenter wp-image-801 size-large resized" src="/images/yellow-furry-lullaby-Kayth-Hughes-02-1024x768.jpg" alt="" width="768" height="576"></span>`,
      `<span class="image-big"><img decoding="async" class="aligncenter wp-image-927 size-large resized" src="/images/yellow-furry-lullaby-FACT-Breakwater-Feb-2022-Rob-Battersby-31-1-1024x683.jpeg" alt="" width="768" height="512"></span>`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="aligncenter wp-image-928 size-large resized" src="/images/yellow-furry-lullaby-FACT-Breakwater-Feb-2022-Rob-Battersby-33-1024x683.jpeg" alt="" width="768" height="512"></span>`,
      `Yellow Furry Lullaby is a storytelling performance that brings awareness of the historical wound around Chinese indentured labour and ongoing exploitation of migrant workers from Asia, interwoven with the children's story 'We're going on a bear hunt' and Korean national mythology depicting a bear woman. Embracing dandelions as symbols of resilience, the performance engages the lineage of trauma amongst East and Southeast Asian communities and offers a tender moment for collective healing.`,
      `*Collaboration with Taey Iohe, photos by Kayt Hughes &amp; Rob Bettersby.`,
      `* The first iteration was presented in the Deptford X festival (2020), and the completed version was performed as part of the exhibition <a href="https://www.fact.co.uk/event/future-ages-will-wonder" target="_blank" rel="noopener">'Future Ages Will Wonder'</a> (FACT Liverpool 2021). The recorded version can be accessed via FACT podcast <a href="https://www.fact.co.uk/resources/2022/01/podcast-gaining-ground-with-youngsook-choi-and-taey-iohe-of-breakwater" target="_blank" rel="noopener">'Gaining Ground Episode 2'</a>.&nbsp;<br><br>`,
    ],
    images: [
      { src: '/images/yellow-furry-lullaby-906F5079-9078-4512-97B1-66F555FA931E.jpg', alt: '' },
      { src: '/images/yellow-furry-lullaby-Kayth-Hughes-02-1024x768.jpg', alt: '' },
      { src: '/images/yellow-furry-lullaby-FACT-Breakwater-Feb-2022-Rob-Battersby-31-1-1024x683.jpeg', alt: '' },
      { src: '/images/yellow-furry-lullaby-FACT-Breakwater-Feb-2022-Rob-Battersby-33-1024x683.jpeg', alt: '' },
    ],
  },
  {
    slug: 'a-mountain-a-bundle-a-spell',
    title: 'A mountain A bundle A spell',
    category: 'works',
    content: [
      `<span class="image-big"><img decoding="async" class="aligncenter wp-image-819 size-large resized" src="/images/a-mountain-a-bundle-a-spell-IMG_8163-1024x1024.jpg" alt="" width="768" height="768"></span>`,
      `<em>A mountain A bundle A spell</em> is a collaborative improvisation that tests out the affectionate narratives through food making gestures. A huge dough for repetitive labour of love and rhythmic sounds, dumpling talisman with aduki beans spell and a gift of the instant noodle package accompanied with a hand-written letter are devised into this interactive performance for gentle and generous space making and healing moment for East and Southeast Asian diaspora.`,
      `* Collaboration with Jessie Jingely, Monica Tolia and Songsoo Kim`,
      `* Presented in the <a href="https://deptfordx.org/event/hyey-performance/" target="_blank" rel="noreferrer noopener">Deptford X Festival 2021</a>.`,
    ],
    images: [
      { src: '/images/a-mountain-a-bundle-a-spell-IMG_7537-2000x1500.jpg', alt: '' },
      { src: '/images/a-mountain-a-bundle-a-spell-IMG_8163-1024x1024.jpg', alt: '' },
    ],
  },
  {
    slug: 'how-to-restore-a-broken-china-vase',
    title: 'How to Restore a Broken China Vase',
    category: 'works',
    content: [
      `What does it means to build East Asian identity in the West?<br><br><em>How to Restore a Broken China Vase</em> explores the answer through the life of Afong Moy, the first East Asian woman migrant to the United States. In 1834, she was 'imported' by two tradesmen in New York for sitting in the exhibition room filled with luxurious 'oriental' merchandise. The exhibition was hugely successful and travelled to every corner of the country. Gaining national fame as the 'Chinese Lady', Afong Moy's body was not only an exhibit for exotic curiosity but also a device to form and feed the Western perception of Asia as feminine, quiet, and submissive subjectivity. Hence, more an ornament, like a piece of ceramics, not a human with voice and agency. This digital piece is a humble attempt to restore Afong Moy's explicitly ornamentalised and fragmented life (and for those whose lived experiences are similar to hers).`,
      `<iframe title="How to Restore a Broken China Vase" src="https://player.vimeo.com/video/505697006?h=52245dd0ac&amp;dnt=1&amp;app_id=122963" width="768" height="432" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen=""></iframe>`,
      `* Collaboration with Naomi Woo, a pianist and conductor&nbsp;`,
      `* Commissioned by Tangram, supported by SOAS University of London.`,
      `* Premiered in the virtual performance symposium <em>New Creativity</em> (2020)`,
    ],
    images: [
      { src: '/images/how-to-restore-a-broken-china-vase-Afong-Moy.jpg', alt: '' },
    ],
  },
  {
    slug: 'not-this-future',
    title: 'Not This Future',
    category: 'works',
    content: [
      `<span class="image-big"><img decoding="async" class="alignnone wp-image-644 size-large resized" src="/images/not-this-future-NTF02-1024x576.jpg" alt="" width="768" height="432"></span>`,
      `<span class="image-big"><img decoding="async" class="alignnone wp-image-646 size-large resized" src="/images/not-this-future-NTF04-1024x576.jpg" alt="" width="768" height="432"></span>`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="alignnone wp-image-645 size-large resized" src="/images/not-this-future-NTF03-1024x576.jpg" alt="" width="768" height="432"></span>`,
      `How can we begin mourning for inexplicably naturalised death? How can we recognise and lick the wounds when the tragedy is considered conveniently inevitable?`,
      `<em>Not This Future</em> facilitates a pseudo shamanic ritual as a political device by holding the grief as a site of solidarity and communal care directed to the victims of hostile environments policy, brutal border control and neo-colonial operation. It commemorates and critically revisits the Essex 39 incident where thirty-nine Vietnamese were found dead in the back of a lorry abandoned by a people smuggler in 2019. As a core part of the commemoration, this spiritual performance accommodates 39 offerings from different parts of the world, gathered through the exclusive call out for those whose creative practice and research weigh on migrant justice and challenge the idea of borders.&nbsp; &nbsp;`,
      `<em>Not This Future&nbsp;</em>is part of Youngsook Choi's ongoing exploration of political spirituality which experiments upon intimate aesthetics of community actions and alternative protests.`,
      `* A series of artist talks that expands on the themes around grief as community solidarity, transnational kinship and communal healing (with Tessa Qiu, Annie Jael Kwan and Ceara Conway, and supported by Heart of Glass, 2021). The edited conversations are available <a href="https://www.heartofglass.org.uk/projects-and-events/projects/not-this-future-1" target="_blank" rel="noopener">here</a>.&nbsp;&nbsp;`,
      `* Offerings from: Adriel Luis, Amal Khalaf, Amit Rai, Annie Jael Kwan, Anouar Kassim, Ayelet Zohar, Bao Vuong, Burong Zeng, Caro Gervay, Cecilia Wee, Cian Dayrit, Cuóng Pham, David Sebastian Lopez Restrepo, Erene Kaptani, Farzana Khan, Georgina Quach, Hai Nguyen , Hina Khan, Hsiao Hung Pai, Ibrahim Abdella, Ido Zohar, Jabez Lam, Joon Lynn Goh, June Lam, Kay Stephens (remember.resist collective), Mariko Hayashi, Mihye Lee, Nia Fekri, Nine Yamamoto-Masson, Rajinder Singh, Richard Streitmatter-Tran, Sajan Mani, Sarnt Utamachote (unthaitled collective), Shzr Ee Tan, Subhas Nair, Sungmee Bae, Taey Iohe, Tamsin Barber, Tomasz Madajczak, Vanessa Scully, Vijay Patel, Vukasin Nedeljkovic, Weng San Sit, Yoonah Han`,
      `* Commissioned by Asia-Art-Activism, supported by Bagri Foundation, Arts Council England and Heart of Glass.`,
      `* First exhibited in the group show <em>Till We Meet Agin IRL</em> (2020, Bagri Foundation), Re-exhibited as part of <em>Remote Working Commission</em> (2021, Heart of Glass) and at S1 Artspace as part of <em>Migration Matters Festival</em> 2021.`,
    ],
    images: [
      { src: '/images/not-this-future-Not-This-Future.jpg', alt: 'Not this future' },
      { src: '/images/not-this-future-NTF02-1024x576.jpg', alt: '' },
      { src: '/images/not-this-future-NTF04-1024x576.jpg', alt: '' },
      { src: '/images/not-this-future-NTF03-1024x576.jpg', alt: '' },
    ],
  },
  {
    slug: 'green-spell',
    title: 'Green Spell',
    category: 'works',
    content: [
      `How have we gotten here…&nbsp; Shifting everything into a digital realm and faux-functioning in Zoom won't save this crisis. It must be the spell and the spell must be broken for the beginning of new chapter. It will require good listening and full reconciliation first to be able to understand where the intention lies, the most challenging part, and then, only then, we might start trying out with an act of care, the long lost sensibility in this profit-driven world.&nbsp;`,
      `<iframe title="Green Spell" src="https://player.vimeo.com/video/431164148?dnt=1&amp;app_id=122963" width="768" height="432" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen=""></iframe>`,
      `* Single channel video with no sound, 2m 58sec (2020)`,
      `* Exhibited in LIGHTBLICK, Kunsthalle am Hamburger, Berline&nbsp;`,
    ],
    images: [
      { src: '/images/green-spell-Y.Choi-Choi_Green-Spell2020-2000X1500px.jpg', alt: '' },
    ],
  },
  {
    slug: 'unapologetic-coughing',
    title: 'Unapologetic Coughing',
    category: 'works',
    content: [
      `<span class="image-big"><img decoding="async" class="alignnone wp-image-528 size-large resized" src="/images/unapologetic-coughing-02-1024x648.jpg" alt="" width="768" height="486"></span>`,
      `<span class="image-big"><img decoding="async" class="alignnone wp-image-529 size-large resized" src="/images/unapologetic-coughing-03-1024x683.jpg" alt="" width="768" height="512"></span>`,
      `<span class="image-big"><img loading="lazy" decoding="async" class="alignnone wp-image-534 size-large resized" src="/images/unapologetic-coughing-11-1024x661.jpg" alt="" width="768" height="496"></span>`,
      `<em>Unapologetic Coughing</em> is a performative response to the hysteria around Coronavirus. It adopts a medical symptom, psychogenic coughing, as a core medium. This least hygienic human gesture will be used for expressing emotional discomfort and mental distress caused by the racialisation of the global pandemic. Having recognised the shocking level of racist attacks on Asian population all over the world including her personal experience, Youngsook delivers this performance with a sense of urgency and to discuss this repetitive narrative of using pandemic hysteria as a justification of violence towards socio-cultural minorities. Unapologetic Coughing invites the audience to take part in a collective reading, sing-along, set of Chinese Whispers, and to most importantly 'own' the right to cough.`,
      `Shown at: Raven Row (2020) as part of '<a href="https://asia-art-activism.net/2020/02/21/un-racialising-the-coronavirus-epidemic/" target="_blank" rel="noopener">Un-racialising the coronavirus epidemic</a>' in support of Asia-Art-Activism , '<a href="https://www.heartofglass.org.uk/projects-and-events/projects/with-for-about-2020" target="_blank" rel="noopener" class="broken_link">With For About 2020</a>' conference in support of Heart of Glass.`,
      `<a href="http://subtropicalasia.com/2020/04/25/owning-the-right-to-cough-a-live-performance-against-the-covid-19-related-racism-crisis/" target="_blank" rel="noopener" class="broken_link">Interview with Subtropical Asia</a> 'Owning the Right to Cough: A Live Performance Against the COVID-19 Related Racism Crisis', Joseph Wang.&nbsp;`,
      `Mentioned in: <em><a href="https://www.artsprofessional.co.uk/magazine/article/can-cultural-organisations-ever-be-radical?fbclid=IwAR3tcZLNU4xn-OGZAI-vyafyqQ4haC5guQzoI7C5XX-SewV6UpVx6bTMWrw" target="_blank" rel="noopener">Can cultural organisations ever be radical?</a></em> (Lois Keidan, Arts Professional),&nbsp; Notes from an infected island (Alicja Rogalska, Ello, in Polish); <a href="https://www.tandfonline.com/toc/rprs20/27/5?nav=tocList" target="_blank" rel="noopener">'Conversation and Convergences for Solidarity', <em>On Solidarity</em></a>, Performance Research Vol. 27 (5), edited by Noyale Colin and Stefanie G. Sachsenmaier.`,
      `Photo Credit: Nurri Kim`,
    ],
    images: [
      { src: '/images/unapologetic-coughing-06-2000x1500.jpg', alt: 'Unapologetic Coughing' },
      { src: '/images/unapologetic-coughing-02-1024x648.jpg', alt: '' },
      { src: '/images/unapologetic-coughing-03-1024x683.jpg', alt: '' },
      { src: '/images/unapologetic-coughing-11-1024x661.jpg', alt: '' },
    ],
  },
  {
    slug: 'emperors-jade-rabbit',
    title: "Emperor's Jade Rabbit",
    category: 'works',
    content: [
      `<span class="image-big"><img decoding="async" class="alignnone wp-image-476 size-large resized" src="/images/emperors-jade-rabbit-EJR01-1024x562.jpg" alt="" width="768" height="422"></span> &nbsp; <span class="image-big"><img decoding="async" class="alignnone wp-image-480 size-large resized" src="/images/emperors-jade-rabbit-EJR05-1024x576.jpg" alt="" width="768" height="432"></span>`,
      `<em><span data-preserver-spaces="true">The Emperor's Jade Rabbit&nbsp;</span></em><span data-preserver-spaces="true">is a calling. A calling for those who feel we live in a society so broken and divided. It devises a collective public reading as an act of resistance against systematic dehumanisation of migrant workers. Inspired by John Burger's critical statement on migrant workers as an interchangeable commodity and hence immortal subject in a global economy, the Emperor's Jade Rabbit weaves the mythological tale of Chinese Moon Rabbit, the immortal creature living on the moon, into the recounts of female migrant cleaners and western superstition/folklore around the use of a broom.&nbsp;</span>`,
      `<span data-preserver-spaces="true">* First performed at </span><em><span data-preserver-spaces="true">Allure of Sorts</span></em><span data-preserver-spaces="true">, co-curated by Scaffold Gallery and Tape Modern, Manchester, 2019</span>`,
      `<span data-preserver-spaces="true">* Restaged in <em>Toward A New Spirituality</em> at Lumen Gallery, London, 2021.</span>`,
    ],
    images: [
      { src: '/images/emperors-jade-rabbit-IMG_7602-2000x1500.jpeg', alt: '' },
      { src: '/images/emperors-jade-rabbit-EJR01-1024x562.jpg', alt: '' },
      { src: '/images/emperors-jade-rabbit-EJR05-1024x576.jpg', alt: '' },
    ],
  },
]

export const contact = {
  paragraphs: [
    `I am a keen collaborator for inter-disciplinary practice or research/development companionship. My current subjects of interest are 1. ecological grief as a site of inter-species witnessing, healing and solidarity, 2. decolonising epistemologies within nature science and geography, and 3. new technological methods as gateways to unlock and discover the languages of other-than-humans.`,
    `As for commissions, I mainly work with/for/about sociocultural margins and children & young people, ideally in a long-term engagement. I am interested in how socially charged art practices can help imagine and build soft infrastructure for care, collective healing and alternative pedagogy. Previous commissions supported by Arts Catalyst, Barbican Centre, Camden Arts Centre, Coventry Biennial, Liverpool Biennial, FACT Liverpool, Heart of Glass, Milton Keynes Art Centre, MK Islamic Arts and Culture, Rich Mix and Arts Council of Korea.`,
    `Potential co-conspirers, please contact me via:`,
  ],
  email: 'selfmadecities@gmail.com',
  instagram: {
    handle: '@young.sook.choi',
    url: 'https://www.instagram.com/young.sook.choi/',
  },
}
