name = "youngsook-admin-worker"
main = "worker/admin-worker.js"
compatibility_date = "2024-09-23"
workers_dev = true

[[kv_namespaces]]
binding = "OTP_KV"
id = "5887203daed140619a100ca93ca1d39d"

[vars]
RESEND_FROM = "onboarding@resend.dev"

# Routes will be added once domain is migrated to Cloudflare
# [[routes]]
# pattern = "admin-worker.youngsookchoi.com/*"
# zone_name = "youngsookchoi.com"
